### ISSUE TITLE
The Sprite class removed from this new version?

### ISSUE THREAD

**Issue by alexwenbj** [GameJs/gamejs#101]
I can't find the Sprite class in the current version, But it was in the old one.Has the Sprite been removed? What is the alternative one?
Thank you.
@oberhamsi

**Comment by oberhamsi** [comment]
it was renamed to SpriteSheet, should be this one https://github.com/GameJs/gamejs/blob/master/src/gamejs/animate.js

**Comment by alexwenbj** [comment]
@oberhamsi Got it.Thank you.
