### ISSUE TITLE
Wrong link in README.md

### ISSUE THREAD

**Issue by kangjung** [GameJs/gamejs#102]
Some links to https://docs.gamejs.org/ do not go to the details page, but to the main screen.

Example)
Click on "pathfinding"
Go to "https://docs.gamejs.org/ " instead of "https://docs.gamejs.org/gamejs/pathfinding/index.html ".

**Comment by oberhamsi** [comment]
i'm afraid the domain was bought by some else and i can't do antying about this. sorry.
