### ISSUE TITLE
Examples not loading..

### ISSUE THREAD

**Issue by mdan312** [GameJs/gamejs#87]
When I double click on any of the HTML files in the examples of folder, I get a "loading" message, but nothing occurs. Tried with iPad/Safari, win7 64bits last Chrome, win7 64bits IE 10.

Tried with file:// and http://

**Comment by ambeam** [comment]
Wow dude!!! So sorry that I've never been there on this account and now I've read all this stuff people posted! :D

This repo is DEAD, this was only for testing purposes :D sorry to all of You ;). My bad this is set to be public repository... I feel stupid for leaving garbage here ;)

Sorry again, I'm going to close this repo now.

**Comment by mdan312** [comment]
Oh I just forgot to build...

**Comment by mdan312** [comment]
Anyway it is the last version...

Cordialement, 

Daniel

**Comment by oberhamsi** [comment]
did i understand you right that in the end it worked because you didn't build? or was there another problem. 

the built gamejs file ships with the zip version. downloading with git and npm requires building. maybe that's not obvious enough :)

**Comment by mdan312** [comment]
Yes I have understood now! Thank you for you work!
