### ISSUE TITLE
Uncaught TypeError: Cannot read property '_canvas' of null

### ISSUE THREAD

**Issue by z3t0** [GameJs/gamejs#89]
```js
SURFACE._canvas.width = canvas.clientWidth;
```

I am making a game using voxel-engine and am using gamejs for keyboard/mouse events at the moment. I get this error from the above line and also a part of the screen is a white rectangle.

![image](https://cloud.githubusercontent.com/assets/9000061/7049685/a6bedb68-ddd8-11e4-88e3-ea62085e9e39.png)

My source code is posted in this [gist](https://gist.github.com/z3t0/f945cb625333241c9eec).

**Comment by oberhamsi** [comment]
i don't see the SURFACE line in the gist. I wonder why you are using the hidden/private property _canvas and not display.setMode()? http://docs.gamejs.org/gamejs/display/

**Comment by z3t0** [comment]
My bad, the error is a part of the bundle.js not index.js I'll add that in a moment.
The reason I am confused as to what to do is that I am not using gamejs for the display, I am using voxel-engine to render, I only want to use the sound/controls from gamejs... Not sure how to proceed

**Comment by z3t0** [comment]
ok added the file to the gist

**Comment by z3t0** [comment]
Is there any way to disable the display properties of gamejs? I basically don't want it to do anything with the display

**Comment by z3t0** [comment]
```html
<canvas id="gjs-canvas" tabindex="1" style="display: block;"></canvas>
```
that's the line that creates the white canvas, now just need to figure out how to stop it from being created

**Comment by z3t0** [comment]
Fixed!

**Comment by z3t0** [comment]
```js
/**
 * Create the master Canvas plane.
 * @ignore
 */
exports.init = function() {
   // create canvas element if not yet present
   var canvas = getCanvas();
   if (!canvas.getAttribute('tabindex')) {
      // to be focusable, tabindex must be set
      canvas.setAttribute("tabindex", 1);
      canvas.focus();
   }
   // remove loader if any;
   var $loader = document.getElementById(LOADER_ID);
   if ($loader) {
      $loader.style.display = "none";
   }
   var $displaySurface = document.getElementById(CANVAS_ID);
   if ($displaySurface) {
      $displaySurface.style.display = 'block';
   }
   // hook into resize
   window.addEventListener("resize", onResize, false);
   return;
};
```
That is what creates the canvas

**Comment by z3t0** [comment]
Can you please add an option to enable/disable display so that I don't have to comment it out manually. Thanks!
