### ISSUE TITLE
Uncaught TypeError: Cannot read property 'display' of undefined

### ISSUE THREAD

**Issue by z3t0** [GameJs/gamejs#91]
```js
gamejs.display.setMode(gamejs.display.POINTERLOCK)
```

**Comment by z3t0** [comment]
The line is copied straight from docs
http://docs.gamejs.org/gamejs/display/index.html

**Comment by z3t0** [comment]
Oh... noob mistake. I thkn

**Comment by z3t0** [comment]
Nope...
```js
var display = gamejs.display.getSurface();
```
gamejs.display seems to be undefined?

**Comment by z3t0** [comment]
The problem was to do with another package.

**Comment by oberhamsi** [comment]
uh, do you know which other package caused problems? i wonder how this kind of problem can happen

**Comment by z3t0** [comment]
Sorry it was just a noob mistake where I tried to set the display before initializing the object :smile:
